spring.application.name=redish
server.port=${SERVER_PORT:8091}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/redish?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:priyanshu}
spring.datasource.password=${DB_PASSWORD:coffee}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.data.jpa.repositories.enabled=false

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.repositories.enabled=false
spring.cache.type=redis

# Useful during POC demos to show cache hits/misses in logs
logging.level.org.springframework.cache.interceptor=TRACE
